# Generated by Django 5.2.1 on 2025-05-24 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
