# Generated by Django 5.2.1 on 2025-05-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_messages_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.JSONField(),
        ),
    ]
