# Generated by Django 5.1.4 on 2025-05-27 09:28

from django.db import migrations, models
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_messages_chat_id_alter_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_id',
            field=models.UUIDField(null=True, editable=False, help_text="Unique identifier for the message")
        )
    ]
