# Generated by Django 5.1.4 on 2025-05-27 09:30

from django.db import migrations, models
from uuid import uuid4

def generate_uuids(apps, schema_editor):
    Message = apps.get_model('chats', 'messages')
    # Only fill the ones that are still NULL
    for msg in Message.objects.filter(message_id__isnull=True):
        msg.message_id = uuid4()
        msg.save(update_fields=['message_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20250527_0928'),
    ]

    operations = [
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
    ]
