# Generated by Django 5.1.4 on 2025-05-27 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20250527_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
        ),

        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False, null=False)
        )
    ]
