# Generated by Django 5.1.4 on 2025-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_messages_message_id_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='initialized_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
